version: '3.6'

networks:
  web:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    depends_on:
      - backend
    volumes:
      - './nginx.conf:/etc/nginx.conf'
    networks:
      - web
  backend:
    build:
      context: ./app

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - web
